Fix SMS listener initialization error
The SMS listener plugin was failing to initialize due to a `TypeError: n.checkPermission is not a function`. This commit addresses the error.